### ISSUE TITLE
useLocation() may be used only in the context of a <Router> component.

### ISSUE THREAD

**Issue by s-baier** [immobiliare/backstage-plugin-gitlab#131]
Hi,

I just updated the plugin to 4.0.1, and now using the following setup:

* backstage 1.10.0
* @immobiliarelabs/backstage-plugin-gitlab-backend 4.0.1
* @immobiliarelabs/backstage-plugin-gitlab 4.0.1

Unfortunately I'm getting the following error now:

```
Error: useLocation() may be used only in the context of a <Router> component.
    at l (webpack-internal:///../../node_modules/@loblaw/backstage-plugin-gitlab/node_modules/react-router-dom/node_modules/react-router/index.js:30:286)
    at H (webpack-internal:///../../node_modules/@loblaw/backstage-plugin-gitlab/node_modules/react-router-dom/node_modules/react-router/index.js:39:299)
    at G (webpack-internal:///../../node_modules/@loblaw/backstage-plugin-gitlab/node_modules/react-router-dom/node_modules/react-router/index.js:43:33)
    at E (webpack-internal:///../../node_modules/@loblaw/backstage-plugin-gitlab/node_modules/react-router-dom/node_modules/react-router/index.js:38:870)
    at renderWithHooks (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:14985:18)
    at mountIndeterminateComponent (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:17811:13)
    at beginWork (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:19049:16)
    at HTMLUnknownElement.callCallback (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:3945:14)
    at Object.invokeGuardedCallbackDev (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:3994:16)
    at invokeGuardedCallback (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:4056:31)
```

Already tried to completely remove & readd the plugin, to ensure I have everything set up as described in the [README](https://github.com/immobiliare/backstage-plugin-gitlab/blob/main/README.md)

**Comment by antoniomuso** [comment]
From which version are you coming? You seem to be using the old `loblaw`  version from logs. In this case, you have to follow the [migration guide](https://github.com/immobiliare/backstage-plugin-gitlab/blob/main/docs/migration-guides.md)
