### ISSUE TITLE
Error: EMFILE: too many open files on @immobiliarelabs\backstage-plugin-gitlab-backend\node_modules\@backstage\backend-app-api\node_modules

### ISSUE THREAD

**Issue by sharadpattanshetti** [immobiliare/backstage-plugin-gitlab#369]
We upgraded to the backstage version 1.20.0 and since then facing this error in our Windows machines. 
Tried to run the same with node v18.18.2 and v18.19.0 as well but same result. 
Any suggestion on how to fix this would be helpful. 

```
Error: EMFILE: too many open files, open 'C:\myworkspace\node_modules\@immobiliarelabs\backstage-plugin-gitlab-backend\node_modules\@backstage\backend-app-api\node_modules\@kubernetes\client-node\dist\gen\model\v1beta2FlowSchema.js'
    at Object.openSync (node:fs:603:3)
    at Object.readFileSync (node:fs:471:35)
    at Object.j (C:\workspace\node_modules\tsx\dist\cjs\index.cjs:1:998)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at Module.Hook._require.Module.require (c:\workspace\node_modules\require-in-the-middle\index.js:188:39)
    at require (node:internal/modules/cjs/helpers:119:18)
    at <anonymous> (c:\workspace\node_modules\@immobiliarelabs\backstage-plugin-gitlab-backend\node_modules\@backstage\backend-app-api\node_modules\@kubernetes\client-node\dist\gen\model\models.js:471:22)
    at Object.<anonymous> (c:\workspace\node_modules\@immobiliarelabs\backstage-plugin-gitlab-backend\node_modules\@backstage\backend-app-api\node_modules\@kubernetes\client-node\dist\gen\model\models.js:1809:20)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Object.j (C:\workspace\node_modules\tsx\dist\cjs\index.cjs:1:1197)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at Module.Hook._require.Module.require (c:\workspace\node_modules\require-in-the-middle\index.js:188:39) {
  errno: -4066,
  syscall: 'open',
  code: 'EMFILE',

```

**Comment by sharadpattanshetti** [comment]
We tried to comment out this plugin code in our backstage instance then the error is gone. Backend is up and running. Can you please suggest a fix for this issue?

**Comment by sharadpattanshetti** [comment]
Thanks for the reply @antoniomuso. Is 6.4.0 the latest version of this plugin which we need update in our package.json?

**Comment by antoniomuso** [comment]
I mean try to upgrade `@backstage/backend-common` package
